# Generated by Django 5.1.7 on 2025-03-28 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Marca Generica', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='Sin categoria', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currencys',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RedirectAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('redirect_count', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('Stores_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tienda Generica', max_length=255)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('search_url', models.CharField(max_length=255)),
                ('custom_search_url', models.CharField(max_length=255)),
                ('has_api', models.BooleanField(default=False)),
                ('Image_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('login_type', models.CharField(choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('Email', 'Email'), ('Apple', 'Apple')], max_length=20)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricesHistory',
            fields=[
                ('price_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Web_repo.currencys')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Producto Generico', max_length=255)),
                ('upc', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=2500)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Web_repo.brand')),
                ('current_lowest_price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Web_repo.priceshistory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='Web_repo.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('Product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='Web_repo.categories')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='Web_repo.products')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProducts',
            fields=[
                ('store_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_keeping_unit', models.CharField(default='Not known', max_length=50, unique=True)),
                ('products_url', models.CharField(max_length=500)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='Web_repo.products')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='Web_repo.stores')),
            ],
        ),
        migrations.AddField(
            model_name='priceshistory',
            name='store_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Web_repo.storeproducts'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('state', models.CharField(default='Unknown', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserHasLiked',
            fields=[
                ('user_has_liked_id', models.AutoField(primary_key=True, serialize=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Web_repo.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('user_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
