# Generated by Django 5.1.7 on 2025-03-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ongoing', 'On going'), ('ends_soon', 'Ends soon'), ('ended', 'Ended')], max_length=20)),
                ('stores', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
