# Generated by Django 5.1.7 on 2025-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='last_price_change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
