# Generated by Django 5.1.6 on 2025-03-08 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0002_remove_user_password_hash_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Marca Generica', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='Sin categoria', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currencys',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('Stores_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tienda Generica', max_length=255)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('search_url', models.CharField(max_length=255)),
                ('custom_search_url', models.CharField(max_length=255)),
                ('has_api', models.BooleanField(default=False)),
                ('Image_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PricesHistory',
            fields=[
                ('price_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Web_repo.currencys')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Producto Generico', max_length=255)),
                ('upc', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=2500)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Web_repo.brand')),
                ('current_lowest_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Web_repo.priceshistory', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='Web_repo.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('Product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='Web_repo.categories')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='Web_repo.products')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProducts',
            fields=[
                ('store_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_keeping_unit', models.CharField(default='Not known', max_length=50, unique=True)),
                ('products_url', models.CharField(max_length=500)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='Web_repo.products')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='Web_repo.stores')),
            ],
        ),
        migrations.AddField(
            model_name='priceshistory',
            name='store_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Web_repo.storeproducts'),
        ),
        migrations.CreateModel(
            name='UserHasLiked',
            fields=[
                ('user_has_liked_id', models.AutoField(primary_key=True, serialize=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Web_repo.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Web_repo.user')),
            ],
        ),
    ]
