# Generated by Django 5.1.6 on 2025-03-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0003_brand_categories_currencys_stores_priceshistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
