# Generated by Django 5.1.6 on 2025-03-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0004_productimage_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproducts',
            name='products_url',
            field=models.CharField(max_length=1500),
        ),
    ]
