# Generated by Django 5.1.6 on 2025-03-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0005_alter_storeproducts_products_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproducts',
            name='stock_keeping_unit',
            field=models.CharField(default='Not known', max_length=50),
        ),
    ]
