# Generated by Django 5.1.6 on 2025-03-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0006_alter_storeproducts_stock_keeping_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceshistory',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
