# Generated by Django 5.1.7 on 2025-03-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0007_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ongoing', 'On Going'), ('ended', 'Ended'), ('ends_soon', 'Ends Soon')], max_length=20)),
                ('store', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RedirectAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('redirect_count', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
