# Generated by Django 5.1.7 on 2025-03-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0007_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
