# Generated by Django 5.2 on 2025-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0007_alter_priceshistory_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationLog',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='RedirectAnalytics',
        ),
        migrations.DeleteModel(
            name='UserRecord',
        ),
        migrations.RemoveField(
            model_name='images',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='general_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='active_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
