# Generated by Django 5.1.7 on 2025-03-27 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0008_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('user_has_liked_id', models.AutoField(primary_key=True, serialize=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('active_notifications', models.BooleanField(default=False)),
                ('price_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_threshold', models.IntegerField(default=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Web_repo.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserHasLiked',
        ),
    ]
