# Generated by Django 5.2 on 2025-04-06 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0008_delete_notificationlog_delete_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_products', to='Web_repo.images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='Web_repo.products'),
        ),
    ]
