# Generated by Django 5.1.7 on 2025-03-27 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0009_userfavorites_delete_userhasliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='current_lowest_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web_repo.priceshistory'),
        ),
    ]
