# Generated by Django 5.2 on 2025-04-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0009_alter_productimage_image_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='Stores_id',
            new_name='store_id',
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(related_name='products', through='Web_repo.ProductCategory', to='Web_repo.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='last_price_change',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
