# Generated by Django 5.2 on 2025-04-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0010_rename_stores_id_stores_store_id_products_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='last_price_change_percentage',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
