# Generated by Django 5.1.7 on 2025-03-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0010_alter_products_current_lowest_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorites',
            old_name='user_has_liked_id',
            new_name='user_favorites_id',
        ),
    ]
