# Generated by Django 5.1.7 on 2025-03-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_repo', '0011_rename_user_has_liked_id_userfavorites_user_favorites_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavorites',
            unique_together={('user_id', 'product_id')},
        ),
    ]
